[package]
name = "poc-pipeline"
version = "0.1.0"
edition = "2021"

[dependencies]
taffy = "0.7.5"
gtk4 = "0.9.5"
parley = { version = "0.2.0", optional = true }
pangocairo = { version = "0.20.7", optional = true }

[features]
default = ["pango"]
pango = ["dep:pangocairo"]
parley = ["dep:parley"]
